name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      with: 
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenv-parallel: true

  job2:
    runs-on: ubuntu-latest
    concurrency:
      group: some-group-name
    defaults: 
      run:
        working-directory: ./example-app
    
    steps:
    - name: Install Dependencies
      run: |
        poetry install --no-root
        
    - name: Poetry Lint
      run: |
        poetry run task lint
      
    - name: Poetry Formatter 
      run: |
        poetry run task formatter
    
    - name: Poetry Security
      run: |
        poetry run task security

      
